# Generated by Django 4.1.5 on 2023-05-06 07:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#ffffff', max_length=9)),
                ('background_color', models.CharField(default='#000000', max_length=9)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 5, 6, 3, 16, 6, 915670))),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 5, 6, 3, 16, 6, 915670))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2023, 5, 6, 3, 16, 6, 915670))),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('owners', models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 5, 6, 3, 16, 6, 920669))),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 5, 6, 3, 16, 6, 920669))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2023, 5, 6, 3, 16, 6, 920669))),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('labels', models.ManyToManyField(blank=True, to='tasks.label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(default='', max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.worker')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(through='tasks.WorkerTask', to='tasks.worker'),
        ),
        migrations.CreateModel(
            name='PrettyKeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#ffffff', max_length=9)),
                ('background_color', models.CharField(default='#000000', max_length=9)),
                ('content', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('is_edited', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 5, 6, 3, 16, 6, 923299))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
